version: '2'

services:
  web:
    restart: always
    build: ./web
    ports:
     - "1880:1880"
    volumes:
     - ./volumes/node-red:/root/.node-red
     - ../motion/volumes/motion/data/:/root/motion
    devices:
     - "/dev/ttyACM0:/dev/ttyACM0"
    network_mode: "host"
